### ISSUE TITLE
Issue with IP

### ISSUE THREAD

**Issue by jsloyer** [hzeller/rpi-matrix-pixelpusher#1]
When I start starting pixel-push I get the following error.

pi@display-pi ~/rpi-matrix-pixelpusher $ sudo ./pixel-push
getting IP address: Cannot assign requested address
IP: 0.0.0.0; MAC: <removed mac>

**Comment by rogerguess** [comment]
I am also getting this error. Any luck? I am only on wireless, not wired.

**Comment by jsloyer** [comment]
Yeah, it turned out the C code was trying to bind to eth0, I changed the C wlan0 and thing worked fine.  Ill go ahead and close...

**Comment by hzeller** [comment]
Good point. I should probably make that a commandline option.

**Comment by rogerguess** [comment]
Thanks, I changed to wlan0 and it worked for me as well. Time to learn about how to push content to it.

**Comment by hzeller** [comment]
I added now a new commandline option '-i' that allows you to set the interface, so in your case
  -i wlan0

(commit 7863c4cf78fb1937ef73c58d7b1ab71c4ee62410)
