### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by snap2222** [hzeller/rpi-matrix-pixelpusher#11]
Hi there, I believe I must be missing something important. I am attempting to run a 32x64 matrix using the Adafruit HAT and controlling them with LEDLab. The software runs well on the Pi and is discovered on my iPad, but I cannot seem to get any sort of display. I'd sincerely appreciate any advice you may have.

Thanks so much.

**Comment by hzeller** [comment]
On 22 August 2016 at 23:01, snap2222 notifications@github.com wrote:

> Hi there, I believe I must be missing something important. I am attempting to run a 32x64 matrix using the Adafruit HAT and controlling them with LEDLab. The software runs well on the Pi and is discovered on my iPad, but I cannot seem to get any sort of display. I'd sincerely appreciate any advice you may have.

Did you change  matrix/lib/Makefile to change the pinout for your Adafruit HAT ?

Cheers,
  Henner.

**Comment by snap2222** [comment]
Hi Henner, 

I did. Do I have to run the MAKE command once again after I make changes to the Makefile? Please forgive my linux noobness. 

Thanks, Damon 

----- Original Message -----

**Comment by hzeller** [comment]
On 23 August 2016 at 08:56, snap2222 notifications@github.com wrote:

> Hi Henner,
> 
> I did. Do I have to run the MAKE command once again after I make changes
> to the Makefile? Please forgive my linux noobness.

yes. To be sure, go to the matrix directory, edit the lib/Makefile and then
recompile.

   cd matrix
   vi lib/Makefile   # or whatever editor you use
   make clean
   make
   cd ..
   make pixel-push

(not all steps are really needed, but this makes it very explicit).

I plan to revise this soon that things are a little more simple, but this
would be the way now.

**Comment by snap2222** [comment]
Thank you again Henner! 

----- Original Message -----

**Comment by snap2222** [comment]
Henner, thank you for helping me out, it works great now! Connected instantly.

The only issue I have is a little lag/slow refresh. Are there ways I can improve the speed?

Damon

**Comment by hzeller** [comment]
You can increase the UDP packet size (it is a commandline option), that
allows to send more content per packet. From Processing, you can go all the
way to the maximum, but if you send from iOS, you are limited to 8192 or so.
