### ISSUE TITLE
Mirrored Image

### ISSUE THREAD

**Issue by snap2222** [hzeller/rpi-matrix-pixelpusher#12]
Hi Henner, I have my display working great except the image is mirrored. Is there a solution?

Thanks.

**Comment by hzeller** [comment]
You could write a transformer and hook it into the transformer chain or simply modify the call to `SetPixel()` with the appropriate math (e.g. if it is mirrored in X direction, then you would say `SetPixel(draw_canvas->width() - x, ...)`

In both cases you need small modifications in the source.

**Comment by snap2222** [comment]
May be beyond my ability, but I will certainly give it a try! 
Damon 

----- Original Message -----
