### ISSUE TITLE
Ghosting and DLSB_PWM_NANOSECONDS

### ISSUE THREAD

**Issue by 7Ds7** [hzeller/rpi-matrix-pixelpusher#14]
I currently am experiencing the ghosting issue explained in 
https://github.com/hzeller/rpi-rgb-led-matrix#changing-parameters-via-command-line-flags
**Ghosting with low --led-pwm-lsb-nanoseconds**

From what i understand ( and i do not understand much sorry in advance :/ ) The current matrix version on the pixelpusher repo does not allow one to set DLSB_PWM_NANOSECONDS in the matrix/lib/Makefile as it was non existent at the time is that right ?

Also, pulling the latest matrix into the pixelpusher i was able to `make` with some warnings although, upon running it quits with a "Segmentation fault error" i guess there must be a reason for pixelpusher's matrix submodule not to be the latest.

Is there any other way or workaround to tackle around this Ghosting issue?

Last and not least a huge thanks to @hzeller for providing hours of fun between pi's, leds and wires :D

**Comment by hzeller** [comment]
Yes, I need to update the pixel pusher to use the latest library when I have a little time this month.

In the meantime, you can change the parameter directly in code and need to recompile. You find it in the matrix/ subdirectory in lib/framebuffer.cc:

https://github.com/hzeller/rpi-rgb-led-matrix/blob/01ec618072ed2d69199a32fdbb11707436a69a9e/lib/framebuffer.cc#L38

**Comment by 7Ds7** [comment]
Thank for pointing me in the right direction.
Although after some time spent tweaking with the values i still have the ghosting effect, only if i increase the value to huge numbers +1000 i won't get the ghosting but the leds stay intermittent.

Hopefully it will be fixed with the latest matrix library.
I will close the issue as it was related to changing led-pwm-lsb-nanoseconds with the current library, many thanks once again.
