### ISSUE TITLE
Running a Single APA102 Strip

### ISSUE THREAD

**Issue by ahlynsky** [hzeller/rpi-matrix-pixelpusher#17]
Hey,

I'm trying to use this to drive a single 50 pixel APA102 strand.  Before i start digging in too much, I'm wondering first if this is possible, and second if anyone else has tried?

Thanks!

- Andrew

**Comment by hzeller** [comment]
This is for an LED matrix, which is entirely different from programmable LED strips like the APA102, which is different but also much easier to control.

For LED strips you want to do something like https://github.com/hzeller/spixels as hardware, then just implement whatever network protocol you'd like to have on top of that (e.g. PixelPusher or FlaschenTaschen).
