### ISSUE TITLE
6 panels problem

### ISSUE THREAD

**Issue by ik0adr** [hzeller/rpi-matrix-pixelpusher#18]
Hello Henner, and many thanks for the very nice work on RGB LED matrices.

I tryed the 6 panels according to the instructions:

   [<][<][<]  }--- Pi connector #1
   [>][>][>]
(-U --led-chain=6 --led-parallel=1).

There is something wrong , the third couple of panels (the left side ones) seem swapped.
I am pretty sure to have arranged them according to the sketch.
Could you please check?
Thanks again!

--Federico

**Comment by hzeller** [comment]
Do you have a picture of how your wiring is on the back and a picture from the font that shows how the swapped picture looks ?

**Comment by fedemartini** [comment]
for the wiring here you are:

![img_1759](https://cloud.githubusercontent.com/assets/664468/24220817/21423500-0f4c-11e7-8896-c3739e4de5e0.JPG)

here is the movie:

[FullSizeRender.mov.zip](https://github.com/hzeller/rpi-matrix-pixelpusher/files/862955/FullSizeRender.mov.zip)

Thanks,

--Federico

**Comment by hzeller** [comment]
With the turned display at the corner, your setup is essentially
```
[V][<][<]
[V][>][>]
```
So this is why these panels are turned in the pixel output. So you need to write a transformer to get these pixels mapped correctly and apply your transformer around here
   https://github.com/hzeller/rpi-matrix-pixelpusher/blob/master/pixel-push.cc#L443

**Comment by ik0adr** [comment]
OK, thanks a lot.
