### ISSUE TITLE
Just FYI: I needed to do this to get pixelpusher to work:

### ISSUE THREAD

**Issue by tychop** [hzeller/rpi-matrix-pixelpusher#19]
I wanted to test LEDLabs ios application with the pixelpusher lib. But whatever I tried, nothing showed up on screen. So I began seeing what could be wrong in my setup.
I started by trying out the supporting rpi-rgb-led-matrix lib standalone:
Result: I was successful at running the rpi-rgb-led-matrix lib to show runtext.ppm on my 4 32x64 led matrices using:
```
pi@raspberrypi:~ $ sudo ~/rpi-rgb-led-matrix/examples-api-use/demo -c8 -D 1 ~/rpi-rgb-led-matrix/examples-api-use/runtext.ppm -m 1
Size: 256x32. Hardware gpio mapping: regular
Read image '/home/pi/rpi-rgb-led-matrix/examples-api-use/runtext.ppm' with 500x32
Press <CTRL-C> to exit and reset LEDs
^CReceived CTRL-C. Exiting.
```

Now on to the pixelpusher lib:
(yes, I cloned recursively, did a ```make``` in the project root, and did a ```make -C matrix/examples-api-use``` as well)
```
pi@raspberrypi:~ $ sudo ~/rpi-matrix-pixelpusher/matrix/examples-api-use/demo -c8 -D 1 ~/rpi-rgb-led-matrix/examples-api-use/runtext.ppm -m 1
Size: 256x32. Hardware gpio mapping: regular
Read image '/home/pi/rpi-matrix-pixelpusher/matrix/examples-api-use/runtext.ppm' with 500x32
Press <CTRL-C> to exit and reset LEDs
^C^C^C^C
```
Unfortunately, the last command does nothing. Not even CTRL-C works (you can see that 'Received CTRL-C. Exiting.' is not being displayed after pressing CTRL-C.

So, I deleted the ```matrix``` dir from ```~/rpi-matrix-pixelpusher/``` and moved ```~/rpi-rgb-led-matrix``` into ```~/rpi-matrix-pixelpusher/``` as ```matrix```.
Then did a ```make```.

Now the demo works, and the pixelpusher also works:
```
pi@raspberrypi:~/rpi-matrix-pixelpusher $ sudo ~/rpi-matrix-pixelpusher/pixel-push -i wlan0 --led-chain=8
wlan0: IP: 192.168.3.43; MAC: b8:27:eb:a2:ee:bd
Display: 256x32 (256 pixels each on 32 strips)
Accepting max 1 strips per packet (with UDP packet limit 1460).
discovery packet size: 106
Press <RETURN> to shut down (supply -d option to run as daemon)
Listening for pixels pushed to port 5078
Starting PixelPusher discovery beacon broadcasting to port 7331
```

**Comment by hzeller** [comment]
Sounds like you have the new Debian Stretch which results in the problem which is fixed in the main library but the latest version is not synced yet in the submodule in the pixelpusher application.

So your solution is the correct way to solve the problem. I'll  update the submodule as soon as I am back at a computer.
