### ISSUE TITLE
Broadcasting problem: Network is unreachable

### ISSUE THREAD

**Issue by lucasParis** [hzeller/rpi-matrix-pixelpusher#6]
The pi is connected directly to my computer by ethernet, they can ping each other and ssh but when starting pixel push it repeatedly prints `Broadcasting problem: Network is unreachable` and can't make the connection to processing.

Could it be the configuration of things like gateway and subnet mask?

I was using it with a wifi router the other day and that was working.

**Comment by hzeller** [comment]
There is an option in which you can provide the interface it should connect to.

**Comment by lucasParis** [comment]
yes  -i eth0 I did try that with no luck
