### ISSUE TITLE
Limits in Proportion?

### ISSUE THREAD

**Issue by snap2222** [hzeller/rpi-matrix-pixelpusher#7]
Just planning a matrix marquee running 3, 32x64 panel and I'm concerned about the limitations in ratio. Can I setup a 32x192 pixel display?

Thank you.

**Comment by hzeller** [comment]
Should be fine - I think the PixelPusher has a limit of 256 LEDs in a row, but you are under that.

**Comment by snap2222** [comment]
Thanks so much!
