### ISSUE TITLE
Pixelpusher protocol

### ISSUE THREAD

**Issue by RcArtSolutions** [hzeller/rpi-matrix-pixelpusher#9]
Hello everybody,

It is a great project and work very fine with _LED Lab_ App.

I have no issues but a question.
Can someone provide a documentation of the pixelpusher protocol? I found nothing in the internet and it is very hard to decode it with wireshark :neckbeard: 

I want to build my own _Controller_, which sends animation via the pixelpusher protocol to the matrix display.

Greetings Elias

**Comment by hzeller** [comment]
I would ask the PixelPusher people directly.
Also, the source code describes things fully, which is usually easier to read than any documentation.
So just read the Java client library they provide (which is then used in the processing framework) or look at the source code here. The [universal-discovery-protocol.h](https://github.com/hzeller/rpi-matrix-pixelpusher/blob/master/universal-discovery-protocol.h) file essentially all you need to know about the protocol, then in pixel-push.cc you see how the interaction happens.

**Comment by RcArtSolutions** [comment]
Thank you for the response.

The keywords "Java client library" have helped me, to find the right repository on Github.
